version: 0.2

env:
  variables:
    S3_BUCKET: "sellercenterprod.exito.com.co"
    CLOUDFRONT_DISTRIBUTION_ID: "E34UHKF31PAFG2"

phases:

  install:
    commands:
      - echo Instalando npm...
      - npm install
      - echo Instalacion de npm finalizada.
      - echo Instalando Angular...
      - npm install -g @angular/cli
      - npm i npm@latest -g
      - echo Instalacion de Angular finalizada.
  build:
    commands:
      - echo Iniciando compilacion...
      - ng build --configuration=Production
      - echo Compilacion terminada.
      - echo Borrando archivos en bucket...
      - aws s3 rm s3://$S3_BUCKET --recursive
      - echo Archivos en bucket borrados.
      - echo Transfiriendo archivos al bucket...
      - aws s3 cp deploy/dist s3://$S3_BUCKET --recursive
      - echo Archivos transferidos.
      - echo Borrando cache en CloudFront...
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo Cache borrado.

artifacts:
  files:
    - '**/*'
  base-directory: deploy/dist
  
  