version: 0.2

env:
  variables:
    S3_BUCKET: "sellercenter.exito.com.co"
    CLOUDFRONT_DISTRIBUTION_ID: "E3462U4NPR8XV7"

phases:

  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y libappindicator1 fonts-liberation
      - sudo apt-get install -y libgconf2-4 libnss3-1d libxss1 libasound2
      - sudo apt-get install -y xdg-utils
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo dpkg -i google-chrome*.deb
      - echo Instalando npm...
      - npm install
      - echo Instalacion de npm finalizada.
      - echo Instalando Angular...
      - npm install -g @angular/cli
      - echo Instalacion de Angular finalizada.
      - ng -v
  build:
    commands:
    
      - echo Iniciando Unit Tests...
      - ng test