version: 0.2

env:
  variables:
    S3_BUCKET: "sellercenter.exito.com.co"

phases:
  build:
    commands:
      - echo Instalando npm...
      - npm install
      - echo Instalacion de npm finalizada.
      - echo Instalando Angular...
      - npm install -g @angular/cli
      - echo Instalacion de Angular finalizada.
      - echo Iniciando compilacion...
      - ng build --prod --output-hashing=all
      - echo Compilacion terminada.
  post_build:
    commands:
      - echo Borrando archivos en bucket...
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo Archivos en bucket borrados.
      - echo Transfiriendo archivos al bucket...
      - aws s3 cp deploy/dist s3://${S3_BUCKET} --recursive
      - echo Archivos transferidos.
      - echo Borrando cache en CloudFront...
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id "E3462U4NPR8XV7" --paths "/*"
      - echo Cache borrado.

artifacts:
  type: S3
  files:
    - '**/*'
  base-directory: deploy/dist
  
  