version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm install -g @angular/cli
      - ng build --prod
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /*

artifacts:
  type: S3
  files:
    - '**/*'
  base-directory: deploy/dist