version: 0.2

phases:

  install:
    commands:
      - npm -v
      - sudo apt-get clean
      - sudo apt-get update
      - sudo apt-get install dpkg
      - sudo apt-get install -y libappindicator1 fonts-liberation
      - sudo apt-get install -y libgconf2-4 libnss3-1d libxss1 libasound2
      - sudo apt-get install -y xdg-utils libgbm1
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo dpkg -i google-chrome*.deb
      - echo Instalando npm...
      - npm install
      - echo Instalacion de npm finalizada.
      - echo Instalando Angular...
      - npm install -g @angular/cli@8.3.29
      - echo Instalacion de Angular finalizada.
      - ng -v
  build:
    commands:
    
      - echo Iniciando Unit Tests...
      - ng test --source-map=false
      # echo Generando documentación... 
      # npm run compodoc 
      # echo Borrando archivos de front en bucket... 
      # aws s3 rm s3://sellercenter.frontdoc.exito.com.co --recursive 
      # echo Archivos de front en bucket borrados. 
      # echo Transfiriendo archivos de front al bucket... 
      # aws s3 cp documentation s3://sellercenter.frontdoc.exito.com.co --recursive 
      # echo Archivos de front transferidos. 
       
artifacts: 
  files: 
    - '**/*' 
    
#cache:
  #paths:
    #- 'node_modules/**/*'
