version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm install -g @angular/cli
      - ng build --prod
  post_build:
    
artifacts:
  type: S3
  files:
    - deploy/dist/**/*
  
    